### ISSUE TITLE
Support webm in the CRAN binaries

### ISSUE THREAD

**Issue by thomasp85** [ropensci/av#10]
RStudio's viewer pane no longer supports mp4, so it would be beneficial to be able to expect av installations to support the webm format. In order for this, ffmpeg needs to be compiled with `--enable-libvpx` on the cran build machines

**Comment by jeroen** [comment]
Fixed for MacOS via https://github.com/autobrew/homebrew-core/commit/d27ce1f64475ef22d4c360ad13d91c8d900ef045

**Comment by jeroen** [comment]
av version 0.4 will have vorbis + vpx + ogg in both windows and macos binaries.
