### ISSUE TITLE
Two different licence files

### ISSUE THREAD

**Issue by stragu** [ropensci/av#28]
Hi there

I was wondering about the two licence files: `LICENSE` and `LICENSE.md`

I assume there should only be one to avoide confusion? Currently, clicking on the "View License" button on GitHub leads to the first one, which makes it look like the default "all rights reserved" copyright is assumed, which is at odds with ROpenSci's principles.

Thanks for the work on this, looking forward to playing with it!

**Comment by jeroen** [comment]
The `LICENSE.md` file is needed for Github and the other one is needed by the CRAN template. This is done automatically when you do `usethis::use_mit_license()`
