### ISSUE TITLE
Installing package on a cluster

### ISSUE THREAD

**Issue by prateeksasan1** [ropensci/av#30]
Hi,

I tried downloading the package on my university cluster. Got the following error 

1. Configuration failed to find the libavfilter library.

2. Line 1: error #2379: cannot open source file "libavfilter/version.h"

**Comment by muschellij2** [comment]
This is almost impossible to diagnose without additional information.  I'd suggest asking the administrator of the cluster to install `libavfilter` or compiling it from source in your home directory or some place where libraries should go.

**Comment by jeroen** [comment]
What OS do you run?

**Comment by prateeksasan1** [comment]
got it fixed. had to ask the administrator to install libavfilter . Thanks
