### ISSUE TITLE
Cluttered Background in Conversion

### ISSUE THREAD

**Issue by johnbde** [ropensci/av#36]
Thanks for this lovely package. Much appreciated. I am trying to convert mp4 to gif. Output file is a bit cluttered in terms of background. Can we also add **delay** argument in the function?

```
library(av)
av_encode_video("demo.mp4", output = "output.gif", framerate = 10, verbose = TRUE)

```

**Comment by jeroen** [comment]
I don't think there is much I can do about this in the bindings. An alternative would be to use `av_video_images()` and then convert those images using the gifski packages.

**Comment by johnbde** [comment]
Thanks for the alternative solution. Works like a charm. Much appreciated!
