### ISSUE TITLE
Breaking API change in ffmpeg-5

### ISSUE THREAD

**Issue by jeroen** [ropensci/av#40]
Our code currently uses the `AVStream->cur_dts` field to synchronize the audio and video streams. However this field was [removed from the public header](https://github.com/FFmpeg/FFmpeg/commit/591b88e6787c4e678237f02a50421d101abd25c2) in ffmpeg-5.

https://github.com/ropensci/av/blob/8f70dcaa67c039a9be52b19584894684a2d22b60/src/video.c#L376-L377

I am not sure what API we need to use instead. @jamrial do you have any suggestion?

**Comment by jamrial** [comment]
If you need something like that field, then you should keep track of the last returned dts from the stream in question within your code.

See https://github.com/FFmpeg/FFmpeg/commit/ab4f299e237708e81af473c88ec5acf0dd13d8eb for how it was handled in ffmpeg.c
